<?php

use Illuminate\Database\Seeder;

class CiudadTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ciudad')->insert(['nombre' => 'Iquique', 'id_region' => '1',]);
        DB::table('ciudad')->insert(['nombre' => 'Alto Hospicio', 'id_region' => '1',]);
        DB::table('ciudad')->insert(['nombre' => 'Pozo Almonte', 'id_region' => '1',]);
        DB::table('ciudad')->insert(['nombre' => 'Camiña', 'id_region' => '1',]);
        DB::table('ciudad')->insert(['nombre' => 'Colchane', 'id_region' => '1',]);
        DB::table('ciudad')->insert(['nombre' => 'Huara', 'id_region' => '1',]);
        DB::table('ciudad')->insert(['nombre' => 'Pica', 'id_region' => '1',]);

        DB::table('ciudad')->insert(['nombre' => 'Antofagasta', 'id_region' => '2',]);
        DB::table('ciudad')->insert(['nombre' => 'Mejillones', 'id_region' => '2',]);
        DB::table('ciudad')->insert(['nombre' => 'Sierra Gorda', 'id_region' => '2',]);
        DB::table('ciudad')->insert(['nombre' => 'Taltal', 'id_region' => '2',]);
        DB::table('ciudad')->insert(['nombre' => 'Calama', 'id_region' => '2',]);
        DB::table('ciudad')->insert(['nombre' => 'Ollagüe', 'id_region' => '2',]);
        DB::table('ciudad')->insert(['nombre' => 'San Pedro de Atacama', 'id_region' => '2',]);
        DB::table('ciudad')->insert(['nombre' => 'Tocopilla', 'id_region' => '2',]);
        DB::table('ciudad')->insert(['nombre' => 'María Elena', 'id_region' => '2',]);

        DB::table('ciudad')->insert(['nombre' => 'Copiapó', 'id_region' => '3',]);
        DB::table('ciudad')->insert(['nombre' => 'Caldera', 'id_region' => '3',]);
        DB::table('ciudad')->insert(['nombre' => 'Tierra Amarilla', 'id_region' => '3',]);
        DB::table('ciudad')->insert(['nombre' => 'Chañaral', 'id_region' => '3',]);
        DB::table('ciudad')->insert(['nombre' => 'Diego de Almagro', 'id_region' => '3',]);
        DB::table('ciudad')->insert(['nombre' => 'Vallenar', 'id_region' => '3',]);
        DB::table('ciudad')->insert(['nombre' => 'Alto del Carmen', 'id_region' => '3',]);
        DB::table('ciudad')->insert(['nombre' => 'Freirina', 'id_region' => '3',]);
        DB::table('ciudad')->insert(['nombre' => 'Huasco', 'id_region' => '3',]);

        DB::table('ciudad')->insert(['nombre' => 'La Serena', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Coquimbo', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Andacollo', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'La Higuera', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Paihuano', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Vicuña', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Illapel', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Canela', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Los Vilos', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Salamanca', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Ovalle', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Combarbalá', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Monte Patria', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Punitaqui', 'id_region' => '4',]);
        DB::table('ciudad')->insert(['nombre' => 'Río Hurtado', 'id_region' => '4',]);

        DB::table('ciudad')->insert(['nombre' => 'Valparaíso', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Casablanca', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Concón', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Juan Fernández', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Quintero', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Viña del Mar', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Isla de Pascua', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Los Andes', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Calle Larga', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Rinconada', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'San Esteban', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'La Ligua', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Cabildo', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Papudo', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Petorca', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Zapallar', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Quillota', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'La Calera', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Hijuelas', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'La Cruz', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Nogales', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'San Antonio', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Algarrobo', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Cartagena', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'El Quisco', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'El Tabo', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Santo Domingo', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'San Felipe', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Catemu', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Llay Llay', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Panquehue', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Putaendo', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Santa Mar{ia', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Quilpué', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Limache', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Olmué', 'id_region' => '5',]);
        DB::table('ciudad')->insert(['nombre' => 'Villa Alemana', 'id_region' => '5',]);

        DB::table('ciudad')->insert(['nombre' => 'Rancagua', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Codegua', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Coinco', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Coltauco', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Doñihue', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Graneros', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Las Cabras', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Machalí', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Malloa', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Mostazal', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Olivar', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pichidegua', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quinta de Tilcoco', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Rengo', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Requínoa', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Vicente', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pichilemu', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'La Estrella', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Litueche', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Marchihue', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Navidad', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Paredones', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Fernando', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chépica', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chimbarongo', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lolol', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Nancagua', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Palmilla', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Peralillo', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Placilla', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pumanque', 'id_region' => '6',]);
    	DB::table('ciudad')->insert(['nombre' => 'Santa Cruz', 'id_region' => '6',]);
    	
    	DB::table('ciudad')->insert(['nombre' => 'Talca', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Constitución', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Curepto', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Empedrado', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Maule', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pelarco', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pencahue', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Río Claro', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Clemente', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Rafael', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cauquenes', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chanco', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pelluhue', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Curicó', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Hualañé', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Licantén', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Molina', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Rauco', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Romeral', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Sagrada Familia', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Teno', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Vichuquén', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Linares', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Colbún', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Longaví', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Parral', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Retiro', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Javier', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Villa Alegre', 'id_region' => '7',]);
    	DB::table('ciudad')->insert(['nombre' => 'Yerbas Buenas', 'id_region' => '7',]);

    	DB::table('ciudad')->insert(['nombre' => 'Concepción', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Coronel', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chiguayante', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Florida', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Hualqui', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lota', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Penco', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Pedro de la Paz', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Santa Juana', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Talcahuano', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Tomé', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Hualpén', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lebu', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Arauco', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cañete', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Contulmo', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Curanilahue', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Los Álamos', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Tirúa', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Los Ángeles', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Antuco', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cabrero', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Laja', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Mulchén', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Nacimiento', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Negrete', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quilaco', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quilleco', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Rosendo', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Santa Bárbara', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Tucapel', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Yumbel', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Alto Biobío', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chillán', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Bulnes', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cobquecura', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Coelemu', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Coihueco', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chillán Viejo', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'El Carmen', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Ninhue', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Ñiquén', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pemuco', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pinto', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Portezuelo', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quillón', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quirihue', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Ránquil', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Carlos', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Fabián', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Ignacio', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Nicolás', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Treguaco', 'id_region' => '8',]);
    	DB::table('ciudad')->insert(['nombre' => 'Yungay', 'id_region' => '8',]);

    	DB::table('ciudad')->insert(['nombre' => 'Temuco', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Carahue', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cunco', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Curarrehue', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Freire', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Galvarino', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Gorbea', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lautaro', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Loncoche', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Melipeuco', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Nueva Imperial', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Padre las Casas', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Perquenco', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pitrufquén', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pucón', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Saavedra', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Teodoro Schmidt', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Toltén', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Vilcún', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Villarrica', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cholchol', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Angol', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Collipulli', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Curacautín', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Ercilla', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lonquimay', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Los Sauces', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lumaco', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Purén', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Renaico', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Traiguén', 'id_region' => '9',]);
    	DB::table('ciudad')->insert(['nombre' => 'Victoria', 'id_region' => '9',]);

    	DB::table('ciudad')->insert(['nombre' => 'Puerto Montt', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Calbuco', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cochamó', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Fresia', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Frutillar', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Los Muermos', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Llanquihue', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Maullín', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Puerto Varas', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Castro', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Ancud', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chonchi', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Curaco de Vélez', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Dalcahue', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Puqueldón', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Queilén', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quellón', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quemchi', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quinchao', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Osorno', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Puerto Octay', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Purranque', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Puyehue', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Río Negro', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Juan de la Costa', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Pablo', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chaitén', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Futaleufú', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Hualaihué', 'id_region' => '10',]);
    	DB::table('ciudad')->insert(['nombre' => 'Palena', 'id_region' => '10',]);

    	DB::table('ciudad')->insert(['nombre' => 'Coyhaique', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lago Verde', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'Aysén', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cisnes', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'Guaitecas', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cochrane', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'O Higgins', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'Tortel', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'Chile Chico', 'id_region' => '11',]);
    	DB::table('ciudad')->insert(['nombre' => 'Río Ibáñez', 'id_region' => '11',]);

    	DB::table('ciudad')->insert(['nombre' => 'Punta Arenas', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Laguna Blanca', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Río Verde', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Gregorio', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cabo de Hornos', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Antártica', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Porvenir', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Primavera', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Timaukel', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Natales', 'id_region' => '12',]);
    	DB::table('ciudad')->insert(['nombre' => 'Torres del Paine', 'id_region' => '12',]);

    	DB::table('ciudad')->insert(['nombre' => 'Santiago', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cerrillos', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Cerro Navia', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Conchalí', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'El Bosque', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Estación Central', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Huechuraba', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Independencia', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'La Cisterna', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'La Florida', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'La Granja', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'La Pintana', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'La Reina', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Las Condes', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lo Barnechea', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lo Espejo', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lo Prado', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Macul', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Maipú', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Ñuñoa', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pedro Aguirre Cerda', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Peñalolén', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Providencia', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pudahuel', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quilicura', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Quinta Normal', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Recoleta', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Renca', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Joaquín', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Miguel', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Ramón', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Vitacura', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Puente Alto', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Pirque', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'San José de Maipo', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Colina', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lampa', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Tiltil', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Bernardo', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Buin', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Calera de Tango', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Paine', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Melipilla', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Alhué', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Curacaví', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'María Pinto', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'San Pedro', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Talagante', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'El Monte', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Isla de Maipo', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Padre Hurtado', 'id_region' => '13',]);
    	DB::table('ciudad')->insert(['nombre' => 'Peñaflor', 'id_region' => '13',]);

    	DB::table('ciudad')->insert(['nombre' => 'Valdivia', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Corral', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lanco', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Los Lagos', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Máfil', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Mariquina', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Paillaco', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Panguipulli', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'La Unión', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Futrono', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Lago Ranco', 'id_region' => '14',]);
    	DB::table('ciudad')->insert(['nombre' => 'Río Bueno', 'id_region' => '14',]);

    	DB::table('ciudad')->insert(['nombre' => 'Arica', 'id_region' => '15',]);
    	DB::table('ciudad')->insert(['nombre' => 'Camarones', 'id_region' => '15',]);
    	DB::table('ciudad')->insert(['nombre' => 'Putre', 'id_region' => '15',]);
    	DB::table('ciudad')->insert(['nombre' => 'General Lagos', 'id_region' => '15',]);
    }
}

